// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/config/filter/network/jres_proxy/v2alpha1/jres_proxy.proto

package envoy_config_filter_network_jres_proxy_v2alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on JresProxy with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *JresProxy) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetStatPrefix()) < 1 {
		return JresProxyValidationError{
			field:  "StatPrefix",
			reason: "value length must be at least 1 bytes",
		}
	}

	if _, ok := ProtocolType_name[int32(m.GetProtocolType())]; !ok {
		return JresProxyValidationError{
			field:  "ProtocolType",
			reason: "value must be one of the defined enum values",
		}
	}

	if _, ok := SerializationType_name[int32(m.GetSerializationType())]; !ok {
		return JresProxyValidationError{
			field:  "SerializationType",
			reason: "value must be one of the defined enum values",
		}
	}

	for idx, item := range m.GetRouteConfig() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JresProxyValidationError{
					field:  fmt.Sprintf("RouteConfig[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetJresFilters() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JresProxyValidationError{
					field:  fmt.Sprintf("JresFilters[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// JresProxyValidationError is the validation error returned by
// JresProxy.Validate if the designated constraints aren't met.
type JresProxyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JresProxyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JresProxyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JresProxyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JresProxyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JresProxyValidationError) ErrorName() string { return "JresProxyValidationError" }

// Error satisfies the builtin error interface
func (e JresProxyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJresProxy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JresProxyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JresProxyValidationError{}

// Validate checks the field values on JresFilter with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *JresFilter) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetName()) < 1 {
		return JresFilterValidationError{
			field:  "Name",
			reason: "value length must be at least 1 bytes",
		}
	}

	if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JresFilterValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// JresFilterValidationError is the validation error returned by
// JresFilter.Validate if the designated constraints aren't met.
type JresFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JresFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JresFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JresFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JresFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JresFilterValidationError) ErrorName() string { return "JresFilterValidationError" }

// Error satisfies the builtin error interface
func (e JresFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJresFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JresFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JresFilterValidationError{}
